language: node_js
node_js:
  - "13"
install:
  - "npm install -g firebase-tools"
script: yarn install && yarn generate && firebase deploy --only hosting:shape-plus
   --token "$FIREBASE_TOKEN"
branches:
  only:
    - master
